"""Task for generating activity descriptions."""
from __future__ import annotations

import json
from typing import Any, Dict

from crewai import Task

from schemas import GeneratedActivityContent


def create_description_task(agent, activity_data: Dict[str, Any]) -> Task:
    """
    Create a task for generating activity title and description.

    Args:
        agent: The agent responsible for this task
        activity_data: Raw activity data from Strava webhook

    Returns:
        Configured Task instance
    """
    object_data = activity_data.get("object_data", {})

    # Detect model type to customize prompt
    model_name = getattr(agent.llm, 'model', '').lower() if hasattr(agent, 'llm') and hasattr(agent.llm, 'model') else ''
    api_base = getattr(agent.llm, 'api_base', '').lower() if hasattr(agent, 'llm') and hasattr(agent.llm, 'api_base') else ''

    # Model-specific prompt adaptations
    if 'glm-4.6' in model_name or 'z.ai' in api_base:
        # GLM-4.6: Very literal, needs extremely explicit instructions
        tool_instructions = """
        ⚡ IMMEDIATE ACTION REQUIRED - NO EXCEPTIONS ⚡

        STEP 1: CALL IntervalsIcu__get_activities RIGHT NOW
        STEP 2: CALL IntervalsIcu__get_activity_details RIGHT AFTER STEP 1
        STEP 3: OUTPUT JSON - NO TALKING

        🚨 CRITICAL: Do NOT explain what you will do. Do NOT say "I will call" or "Now I'll fetch".
        🚨 JUST MAKE THE CALLS IMMEDIATELY!

        This is NOT a suggestion - this is a MANDATORY sequence!
        """
        json_instruction = """
        🛑 STOP TALKING - OUTPUT JSON ONLY:
        {{"title": "🚴 Ride", "description": "Description\\n\\nGenerated by AI", "workout_type": "Ride", "key_metrics": {{"power": "275W"}}}}
        """
    elif 'claude' in model_name or 'anthropic' in api_base:
        # Claude: Good at following instructions, needs clear structure
        tool_instructions = """
        📋 TOOL WORKFLOW (Claude):

        Step 1: Call IntervalsIcu__get_activities
        Step 2: Call IntervalsIcu__get_activity_details with the ID
        Step 3: Generate final JSON

        Execute these steps in order without explanatory text between them.
        """
        json_instruction = """
        📤 FINAL OUTPUT:
        Provide only the JSON object with the required fields.
        """
    else:
        # Default/generic models (GPT, etc.)
        tool_instructions = """
        🔧 TOOL SEQUENCE:

        Execute these tools in order:
        1. IntervalsIcu__get_activities
        2. IntervalsIcu__get_activity_details (using the ID from step 1)

        Then generate the final JSON output.
        """
        json_instruction = """
        ✅ FINAL STEP:
        Return the JSON object only.
        """
    strava_id = object_data.get("id")
    activity_type = object_data.get("type", "Run")
    distance = object_data.get("distance", 0) / 1000  # Convert to km
    moving_time = object_data.get("moving_time", 0)
    moving_time_min = moving_time / 60  # Convert to minutes
    start_date = object_data.get("start_date_local")
    
    # Calculate average pace (min/km)
    avg_pace_min_km = (moving_time / 60) / distance if distance > 0 else 0
    pace_min = int(avg_pace_min_km)
    pace_sec = int((avg_pace_min_km - pace_min) * 60)

    # Extract date for Intervals.icu lookup
    start_date_str = start_date.split('T')[0] if start_date and 'T' in start_date else start_date

    description = f"""
    Analyze the Strava activity below and craft an engaging English summary.

    ACTIVITY SNAPSHOT:
    - Strava Activity ID: {strava_id}
    - Sport Type: {activity_type}
    - Distance: {distance:.2f} km
    - Moving Duration: {moving_time_min:.0f} minutes
    - Average Pace: {pace_min}:{pace_sec:02d} /km
    - Local Start Time: {start_date}
    - Activity Date: {start_date_str}

    RAW PAYLOAD (for additional context):
    {json.dumps(object_data, indent=2)}

    YOUR MISSION:

    {tool_instructions}

    1. IMMEDIATELY MAKE THESE 2 CALLS - NO EXCEPTIONS:

        CALL NOW: IntervalsIcu__get_activities with {{"start_date": "{start_date_str}", "end_date": "{start_date_str}", "limit": 10}}
        CALL NEXT: IntervalsIcu__get_activity_details with the ID you get

        ⚠️  AFTER 2 CALLS: Output JSON immediately. No explanations!

    2. PRODUCE A TITLE (≤ 50 characters)
        - Highlight the workout intent or key achievement
        - Include 1-2 relevant emojis for energy
        - Keep wording natural and punchy

    3. PRODUCE A DESCRIPTION (≤ 500 characters)
        - Open with the workout goal/type
        - Summarise the structure (warm-up, blocks, cool-down)
        - Mention 2-3 concrete metrics (pace, HR, splits, power)
        - Close with a short feeling/mindset note
        - End with the watermark "Generated by AI" on a new line
        - Preserve readability with short sentences or line breaks

    4. CLASSIFY THE WORKOUT
        - Choose the best matching type (Easy Run, Tempo Run, Intervals, Long Run, Recovery, etc.)

    OUTPUT CONTRACT:
    - After gathering data (or after 3 tool calls), OUTPUT THE FINAL JSON IMMEDIATELY
    - Respond strictly with valid JSON matching the GeneratedActivityContent schema
    - Do not wrap the JSON in markdown fences
    - Respect character limits and ensure emojis render correctly
    - DO NOT continue calling tools endlessly - use max 3-5 tool calls then STOP

    CRITICAL FINAL ACTION:
    After retrieving and analyzing all data (or reaching tool limit), you MUST output a JSON object with this exact structure:
    {{
        "title": "Activity title with emoji",
        "description": "Activity description text\\n\\nGenerated by AI",
        "workout_type": "Workout classification",
        "key_metrics": {{"metric_name": "value", ...}}
    }}

    Do NOT include any explanatory text, thoughts, or reasoning in your final output.
    Your final message must be ONLY the JSON object, nothing else.

    {json_instruction}
    """
    
    return Task(
        description=description,
        agent=agent,
        expected_output=(
            'ONLY a JSON object starting with { and ending with }. NO other text.\n'
            'Required fields:\n'
            '- "title": activity title with emoji (≤50 chars)\n'
            '- "description": description ending with "Generated by AI"\n'
            '- "workout_type": e.g. "Tempo", "Intervals", "Easy Ride"\n'
            '- "key_metrics": dict of metrics\n\n'
            'Example:\n'
            '{"title": "🚴 Lunch Ride 53K", "description": "Zone 2 endurance ride...\\n\\nGenerated by AI", '
            '"workout_type": "Endurance Ride", "key_metrics": {"avg_power": "278W", "avg_hr": "148 bpm"}}\n\n'
            'FORBIDDEN: explanations, "Perfect!", "I found...", "Let me...", thinking text.'
        ),
        # CRITICAL: output_json disables tool calling! Must parse JSON manually instead.
        # output_json=GeneratedActivityContent,
    )
