"""Task for generating activity descriptions."""
from __future__ import annotations

import json
from typing import Any, Dict

from crewai import Task

from schemas import GeneratedActivityContent


def create_description_task(agent, activity_data: Dict[str, Any]) -> Task:
    """
    Create a task for generating activity title and description.
    
    Args:
        agent: The agent responsible for this task
        activity_data: Raw activity data from Strava webhook
        
    Returns:
        Configured Task instance
    """
    object_data = activity_data.get("object_data", {})
    strava_id = object_data.get("id")
    activity_type = object_data.get("type", "Run")
    distance = object_data.get("distance", 0) / 1000  # Convert to km
    moving_time = object_data.get("moving_time", 0)
    moving_time_min = moving_time / 60  # Convert to minutes
    start_date = object_data.get("start_date_local")
    
    # Calculate average pace (min/km)
    avg_pace_min_km = (moving_time / 60) / distance if distance > 0 else 0
    pace_min = int(avg_pace_min_km)
    pace_sec = int((avg_pace_min_km - pace_min) * 60)

    # Extract date for Intervals.icu lookup
    start_date_str = start_date.split('T')[0] if start_date and 'T' in start_date else start_date

    description = f"""
    Analyze the Strava activity below and craft an engaging English summary.

    ACTIVITY SNAPSHOT:
    - Strava Activity ID: {strava_id}
    - Sport Type: {activity_type}
    - Distance: {distance:.2f} km
    - Moving Duration: {moving_time_min:.0f} minutes
    - Average Pace: {pace_min}:{pace_sec:02d} /km
    - Local Start Time: {start_date}
    - Activity Date: {start_date_str}

    RAW PAYLOAD (for additional context):
    {json.dumps(object_data, indent=2)}

    YOUR MISSION:

    1. FIND INTERVALS.ICU ACTIVITY ID (CRITICAL STEP)
        ⚠️  IMPORTANT: Strava ID ({strava_id}) is NOT the same as Intervals.icu ID!

        Follow these steps to find the correct Intervals.icu activity:

        a) Call IntervalsIcu__get_activities with:
           - start_date: "{start_date_str}"
           - end_date: "{start_date_str}"
           - limit: 10

        b) Find the matching activity by comparing:
           - Distance: {distance:.2f} km
           - Duration: ~{moving_time_min:.0f} minutes
           - Start time: {start_date}

        c) Extract the Intervals.icu activity ID from the matched activity
           (typically format: "i{{athlete_id}}-{{date}}-{{sequence}}")

    2. USE INTERVALS.ICU TOOLS FOR DATA ENRICHMENT
        Once you have the correct Intervals.icu activity ID:
        - Call IntervalsIcu__get_activity_details with the Intervals.icu activity_id
        - Call IntervalsIcu__get_activity_intervals with the Intervals.icu activity_id
        - Combine Strava + Intervals insights to detect workout intent (tempo, intervals, easy, etc.)

    3. PRODUCE A TITLE (≤ 50 characters)
        - Highlight the workout intent or key achievement
        - Include 1-2 relevant emojis for energy
        - Keep wording natural and punchy

    4. PRODUCE A DESCRIPTION (≤ 500 characters)
        - Open with the workout goal/type
        - Summarise the structure (warm-up, blocks, cool-down)
        - Mention 2-3 concrete metrics (pace, HR, splits, feeling)
        - Close with a short feeling/mindset note
        - End with the watermark "Generated by AI" on a new line
        - Preserve readability with short sentences or line breaks

    5. CLASSIFY THE WORKOUT
        - Choose the best matching type (Easy Run, Tempo Run, Intervals, Long Run, Recovery, Fartlek, Race, etc.)

    OUTPUT CONTRACT:
    - Respond strictly with valid JSON matching the GeneratedActivityContent schema
    - Do not wrap the JSON in markdown fences
    - Respect character limits and ensure emojis render correctly
    """
    
    return Task(
        description=description,
        agent=agent,
        expected_output=
        "Valid JSON adhering to the GeneratedActivityContent schema (title, description, workout_type, key_metrics)",
        output_json=GeneratedActivityContent,
    )
