"""Task for the Description Reviewer to create activity descriptions from raw data.

Part of the Supervisor/Executor/Reviewer pattern for DESCRIPTION.
"""

from __future__ import annotations

import json
from typing import Any, Dict

from crewai import Task


def create_description_reviewer_task(
    agent: Any,
    activity_data: Dict[str, Any],
    raw_activity_data: Dict[str, Any],
) -> Task:
    """
    Create a task for the Reviewer to create activity description from raw data.

    Args:
        agent: The Reviewer agent
        activity_data: Original activity data from Strava webhook
        raw_activity_data: Raw data from the Executor

    Returns:
        Configured Task instance
    """
    object_data = activity_data.get("object_data", {})
    strava_id = str(object_data.get("id", "unknown"))
    activity_type = object_data.get("type", "Run")
    distance = object_data.get("distance", 0) / 1000
    moving_time = object_data.get("moving_time", 0) / 60

    # Format the raw data for the task description
    # Truncate if too large to avoid context overflow
    raw_data_str = json.dumps(raw_activity_data, indent=2)
    if len(raw_data_str) > 15000:
        raw_data_str = raw_data_str[:15000] + "\n... [truncated for brevity]"

    description = f"""Create an engaging activity title and description from the raw data.

**YOUR ROLE**: You are the REVIEWER. You ANALYZE the raw data and create the final output.
You do NOT make any tool calls.

ORIGINAL STRAVA ACTIVITY:
- Strava ID: {strava_id}
- Type: {activity_type}
- Distance: {distance:.2f} km
- Moving Time: {moving_time:.0f} minutes

RAW ACTIVITY DATA FROM EXECUTOR:
{raw_data_str}

YOUR TASK:
1. Parse the raw data to extract training metrics
2. Identify the workout type and structure
3. Find key metrics worth highlighting (pace, HR, power, TSS)
4. Check for CORE temperature data and assess thermal stress
5. Create an engaging title (≤50 characters with emojis)
6. Write a compelling description (≤500 characters)
7. Return the final GeneratedActivityContent JSON

TITLE GUIDELINES (≤50 chars):
- Start with 1-2 relevant emojis (🏃 for run, 🚴 for ride)
- Include workout type or key achievement
- Be punchy and natural

DESCRIPTION GUIDELINES (≤500 chars):
- Open with workout goal/type
- Summarize structure briefly
- Include 2-3 key metrics
- Mention CORE temp if significant (≥39°C or rise ≥1.5°C)
- End with "Generated by AI" on new line

OUTPUT REQUIREMENTS - GeneratedActivityContent JSON:

Return a JSON object with this exact structure:
```json
{{
  "title": "🏃 Tempo Run 12K - Strong Finish",
  "description": "Solid tempo session targeting Z3-Z4. Warm-up 2km, then 8km at 4:45/km pace, cool-down 2km. HR avg 155bpm, peaked at 172bpm during the final push. Legs felt responsive after yesterday's rest.\\n\\nGenerated by AI",
  "workout_type": "Tempo Run",
  "key_metrics": {{
    "distance": "12.3 km",
    "avg_pace": "4:52 /km",
    "avg_hr": "155 bpm",
    "max_hr": "172 bpm"
  }}
}}
```

CRITICAL:
- Title MUST be ≤50 characters
- Description MUST be ≤500 characters
- Description MUST end with "Generated by AI"
- Use actual data from raw_activity_data, not placeholders
- Include CORE temperature in description only if significant

Return ONLY the JSON object, no explanations."""

    return Task(
        description=description,
        agent=agent,
        expected_output="""Complete JSON object with activity description.
Format: {"title": "...", "description": "...\\n\\nGenerated by AI", "workout_type": "...", "key_metrics": {...}}
NO markdown fences, NO explanatory text, ONLY the JSON object.""",
    )
