#!/bin/bash
# Script to help set up GitHub secrets for CI/CD
# Usage: ./scripts/setup_github_secrets.sh

echo "=========================================="
echo "GitHub Secrets Setup Helper"
echo "=========================================="
echo ""
echo "GitHub Actions requires the following secrets to be configured:"
echo ""
echo "Repository: emottet/crew (assumed)"
echo "Path: Settings → Secrets and variables → Actions → New repository secret"
echo ""
echo "Required secrets:"
echo "----------------"
echo ""
echo "1. OPENAI_API_BASE"
echo "2. OPENAI_API_KEY"
echo "3. MCP_API_KEY"
echo "4. STRAVA_MCP_SERVER_URL"
echo "5. INTERVALS_MCP_SERVER_URL"
echo "6. METEO_MCP_SERVER_URL"
echo "7. TOOLBOX_MCP_SERVER_URL"
echo ""
echo "NEW (for n8n workflows):"
echo "8. INTERVALS_ICU_API_KEY (Base64-encoded 'API_KEY:your_key')"
echo "9. TELEGRAM_CHAT_ID (Your Telegram chat ID)"
echo "10. TELEGRAM_CREDENTIAL_ID (The ID of your Telegram credentials in n8n)"
echo "11. N8N_API_URL (URL of your n8n instance)"
echo "12. N8N_API_KEY (API key for your n8n instance)"
echo ""
echo "=========================================="
echo "Next steps:"
echo "=========================================="
echo ""
echo "1. Go to: https://github.com/emottet/crew/settings/secrets/actions"
echo "2. Click 'New repository secret'"
echo "3. Add each secret above with its name and value"
echo ""
echo "Or use GitHub CLI (gh):"
echo "----------------------"
echo ""
echo "gh secret set OPENAI_API_BASE --body \"https://ccproxy.emottet.com/v1\""
echo "gh secret set OPENAI_API_KEY --body \"...\""
echo "gh secret set INTERVALS_ICU_API_KEY --body \"...\""
echo "# ... and so on for other secrets"
echo ""
